

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SPRITE_SCALING = 0.2
UPDATES_PER_FRAME = 8
TILE_SCALING = 0.2
PLAYER_MOVEMENT_SPEED = 5
PLAYER_BULLET_SPEED = 10

ENEMY_BULLET_SPEED = 5

GRAVITY = 1
SCREEN_TITLE = "rusty tank against the crazy machines"
